name: Demo Pipeline

on:
  push:
   branches:
    - main

jobs:
   pipeline:
    name: "CI/CD for spring application"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"
    
     #Bump version
      - name: Dry-Run Bump version
        id: tag-version
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: true  

      #Java environment 
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

     #Build using Maven
      - name: Build with Maven
        run: | 
          mvn versions:set -DnewVersion=${{ steps.tag-version.outputs.new_tag }} 
          mvn versions:commit 
          mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #Create new Github Tag
      - name: Create new Tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #Creating the Github release
#      - name: Create a Release
#        uses: elgohr/Github-Release-Action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
#        with:
#          args: ${{ steps.tag-version.outputs.new_tag }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag-version.outputs.new_tag }}
          release_name: Release ${{ steps.tag-version.outputs.new_tag }}
          body: |
            Changes in this Release - ${{ steps.tag-version.outputs.new_tag }}
            - Demo of the application
            - Verification of the application